language: java
sudo: false
os:
  - osx
jdk:
  - openjdk11
env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "oyTRuQZSYNb2NvibPBn7WG2EYYAyEp+mO/LCcj5cYj2HScQ2p35///X5jMURU/Q+WP3rJGXdZEQWLHiqc4JVJ87/wabVAZlrpzut2RDbsVVG2ZnxBgiLvwtc0zPuI+RYO93XGS4qVtUPhgXwGVnnqR8PJQa0nfilPX+GxTEzNhoId91hbQLpxto3eLEh7yTKaxxMaK1aiBJZamlGzIwHi5TaJIR4EjU85Bn7MQWAtQ5CjS12EO9iyYhyFNJf0fqlvxYO+UMxUttzjGLSlA93TmCFxypuujOz1D5eXoVMi5calXuA0N4/IBhbWeqnuT4JkH6ukqLY6QtH2j2BH9rq+YAD35U2JME2UoP4Et9hT5gtps2PyXj1Pjpz0nh3LsiDJSrruzBNJ7SB9nkReDf6eVRwo8KvLbdSZzRRSnn1xCz2AyHQzSaE5MTXGcaSZ7H/AsZPy5J5GCnXFJlrLUx+QXlaqqBboD4WAUCE/8/j+4OcPz6r/pGzJ4RudXySf8aC52439VBpvZTew9ayu07ia4tr9UVNYG87tC/oCKIfAIL4ToXkml2MNu3jgnGo0Xy1gVs50ftRr4sQMuWDrjxNfcK4432kEicxWaGSnoZkQjnPYCWElQ6bVOim6LJq5cJf7v1WOwMcOkRJlNWIH6xQmBH1cOhB3rBDwtBG3fnVIkY="
    # OSSRH_JIRA_PASSWORD
    - secure: "Ip8MCZWoSolKLvwAc91Vh1V++1/TME5yH50qxpziN97DNDhVHbLlUBuag9GlEa7DNTX/Zpj1AGUcXurVb1fNmjRs3ZIKSDfsKmu/PdNkt44rQKLklsQfHPmrj91+CHC/5si8VNngmNz4eBAVBOmLOymzhutAnIls7ZzkTRhopnGJNXRj4iy+rW3t3KztKguyCZSDBYfutqgcTstFGQKb0xj1FXLNb8oNNBubDal3vXMKsvGPFbuClByLc4+VR6UJp1PYw+1HpWX4csbnBtZa2AiLdROvJe5rUb23nczFB+6XzbFYUsKIQYSUwtuviP+vuT348Zw88mNjCVrgn5LSXfltnrofCpKw/6FLSWijibEp6+Sw6E9Kw2Xbdz08xh5AxVRToVcQm1EYjFnia1PJLozy+fdQYAfboefHgu6CaZiUdECRGh5dc2500QOZbOsDAgt51D0PPKREJ0HFgPNwx1dmCf7nkhlrjAzRWpi3vQuNnZM241qaoFqwJGwW5cOUpD9kp4/5EtlTJ9eBrths5jP6GeOUAWBSHLkgp0dmh429YUISxMHDq1/UZLtpGtR76dGTuhvUVD9DLSa3Zw5sTekLLXTaBN/4YHXenYMNzN+5vkqQOBQ+2bA+2DASxO5/9o+KZ5ha/VHH8KmA2wDkjh1PZNWnDdQ5Z/hLYNBYLaU="
    # GPG_KEY_NAME
    - secure: "ogEbUVU1KSlnOyvjRDVhnHnMRJ9gGufDDCmv0WGogecT8sncL+PaQn0UWy6VWmAzewpUifr7Ku89684BXdMOwJBbJz6oOCXikJRu52kzZfDYO5j76dtfA7dY0PcKWT5dg3Yc19HFhRW+ItoVy0JZPZMblYdLzsng8XhHh2Ix+2eXak/+bkNlfyBjdZbnyGVfMd23VKbCIFi/TbLHJiasJTtojDnrfcrcaBA1ooE3Yoo6FO00dZxhqVORv1OYYSZSgCyOidgO+Mqg6yNvvUN26yUrmhSRXQRK0jeBNcoPUor9jrjXIxGgCr7O22M0V/h+1yT3W4ixDUh3BSzFsoyzHl3jydgPPRDJmDY1CCATytbvHcKsnhoBOpM2CIFlLVEot/AeRWzoHRXrm/hTVk0wisocOen9Q97P8o4sPIjpcqUlkWOt5Ax7WNzuZKDnYj2A6tTOIXjhnhgXM4TqLKnMVAihMi6LzIVXE+vTRgC8GaU5MNTMVxTefFPxeoL07+/mbfR+bZXabDI1LCFrBUf6Sq303H+5YaAz9nOm4YOklHE56CApxhz/qA1D4YjKEEh5Hu3J/9Kocdj/qGyosHXQ8aGdWH/pZ1LMAqcmvb7aVjpIfZG4ECi4baYHPzpJ576LZRXmz8bMjy8hFI/kL+4tqNha3KZfnFJVDGPU7hz13Mo="
    # GPG_PASSPHRASE
    - secure: "C//8XoS9ZsJN8D3uDm3MoVU6bMtc94zEqnW54BUeGhZpxa2i9OhXxAJ0kUFj0mMX6OvE4whO5aDDaGpLV6NYQkpMMBStp5EhkSQN4Q3PvQHwUk0DkPeAOx+r9NVU296M3jsI3b6ZH/il3W5Eyz7fRoZi9dx8J1tJiz5R/di6r1b33VPM7gJssPEy+89a5RnPRbHaekUZJ8b6vafIZPYRX/hShd12cDM5z4AacdeAgaJOq3JUPOi+jJJL/8wG7h4c+2KK16J5H0gjxSxKlb5ygnyiH6JEKcLyvJbl/FyVzgUYRb4L/uREF3VCvRn4hzTsD011RPOnNORtx9P1tvnaza5sCM/8WJ4mK2wgxndsv1BA7T/inTltfxNt2WJnmvI7rq+f45+0LrSCfNZ6PBv4uGdB8Tconan8Cz/oNlqILsHkAxh+P9qQdXU9KH7Tb23c4mWtLI19ZnkJtd3Yr3U7XnsrNJV/25mGpusejnICWTrW40alB7ICl3hdGk/RCBDIHSvCCWyU5wvLuQXczipVLqDKrqV99NZd7x4Ur2KrgALtzAkVnhgXYGMiA0VnQhc20/4j+iQ0KjQIp4B6HHIvMUurl3vpddMY7mUxz49ePpN1GZmKz0a1BPN8BI1TjGKtxltzKWX0KmUVjqQHfJ8rISGX4MqeFa0yRnvbK32PGkY="
stages:
  - name: deploy
    if: branch = master
after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
