language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "G8xT4yNY0aBHHxpf7/zioSkOom1uN+B4n/FUXAnZPRvHD30pLbDp2bCkDMJjFQZuTwoBxp3hOLlsGA6HHhY23dZiKbKbwjxGWWnCMuNWxaKEk58thfFIVBgJ6cwtu5+paST41ILDnqTHatc7bS+xrfCVqJgta6xYiYDmxOrrtGOOQCyiM4Sn9PRb0JK8pehSmhgxjS7s+h2vKBwvkJi4d/1IgHI0VmiAHapbUABo4mfjj+D3KalkmPDrRNqwqbzkzndqVo+TW21PbbF2FUwP6D1HgvSEOnojTRkbXMNPNb5BebF8eAX3C72PslSgOD1Y6nXQoFoyK605JpwApzbz6kDaTPomWMJ9Ch2pQY1Mss8xZ/A6rJIvrSmrfAQWDSJjkNdCWGP6fI56CUTOsfKx9sgqvCiXV5wgpMBgpPpSWOXZdWuZLOwICoWTJlaw/iqTWd4iVfsKSaqcsaRKxUAkZ+AvKzaqNhmvsBDPlFszuzhTcq1x/3hcQCynQLCRzNOMupGcPg/9hATV5iagaGtLv8ScVCUcNz4S8ZuUpWFKSLp0GYuqJRezKjgu5A+fbjZ6r9FHEHDR2Rtx5zlk/uBFIWvgQObp5tfamqvYcoxoyPfNVD5+WPixFbpl0Rr46V2blBMd3b5htv4D2tAdti4P8cjGsz5IzGQ1VAgmAfMkqnA="
    # OSSRH_JIRA_PASSWORD
    - secure: "XFlSU4zJ4GAMnnSOtr/3l+68LOYboL3xC3l5T//IfKXAA+MCcmTXV9OBVYUt0Brj8w636kuyTDfiiQXjxMJDAoWG0lyDfxwhalNLrQnvz/JZAjQ9XvOni9YoAJkrqRnuMkhrnxbTpS+8/wbsBAv1a6/ZgN2BCxxSDyVK7Lkw5l/rsXQWni0kkEPUh3LdtB7yjtriq84qG81JoUgKzNIBES8yDwI9uyyStE0z0oiokXvw9t8HWv991lie7Db3HJz5Q+W1syDURu4CAQ84zcRKjIs5poZYtGAXVXJJTyc+mJn1GiEkn05zmPL7rHzpZndKhUcqwTgonNcpc2UUSOKuPTfrLFcmISow0Z7CLasSr2LaS7Wxs/t9iia4fRPIkCNDrn5gYPro5B1f8FExZLnJxg/MyvsadnyXjCnPTPFkgIa5aXAo9thRuyphVbWKNy21WR8ql+6aMkOwnU2wLAGUrpf8mvCGys4qpv2ZusLvsbVop2T72Q9XjwbIjkNA32sCt3RUMa/TUwI4UE4tV4/nb9zXNUQt8pwpegSE5ePvnhngykyqPH4osdlinMKfBLuxex7gWUm+L3IliB8+83hzhVO4yuJf1T98M0e8xdQ6xvdOOQo/kPY6kmvrWgWaq83YrkRXELL5QldpL1TCKUGMpDdE8GrrGgfs7X+ivB/jsII="
    # GPG_KEY_NAME
    - secure: "ogEbUVU1KSlnOyvjRDVhnHnMRJ9gGufDDCmv0WGogecT8sncL+PaQn0UWy6VWmAzewpUifr7Ku89684BXdMOwJBbJz6oOCXikJRu52kzZfDYO5j76dtfA7dY0PcKWT5dg3Yc19HFhRW+ItoVy0JZPZMblYdLzsng8XhHh2Ix+2eXak/+bkNlfyBjdZbnyGVfMd23VKbCIFi/TbLHJiasJTtojDnrfcrcaBA1ooE3Yoo6FO00dZxhqVORv1OYYSZSgCyOidgO+Mqg6yNvvUN26yUrmhSRXQRK0jeBNcoPUor9jrjXIxGgCr7O22M0V/h+1yT3W4ixDUh3BSzFsoyzHl3jydgPPRDJmDY1CCATytbvHcKsnhoBOpM2CIFlLVEot/AeRWzoHRXrm/hTVk0wisocOen9Q97P8o4sPIjpcqUlkWOt5Ax7WNzuZKDnYj2A6tTOIXjhnhgXM4TqLKnMVAihMi6LzIVXE+vTRgC8GaU5MNTMVxTefFPxeoL07+/mbfR+bZXabDI1LCFrBUf6Sq303H+5YaAz9nOm4YOklHE56CApxhz/qA1D4YjKEEh5Hu3J/9Kocdj/qGyosHXQ8aGdWH/pZ1LMAqcmvb7aVjpIfZG4ECi4baYHPzpJ576LZRXmz8bMjy8hFI/kL+4tqNha3KZfnFJVDGPU7hz13Mo="
    # GPG_PASSPHRASE
    - secure: "C//8XoS9ZsJN8D3uDm3MoVU6bMtc94zEqnW54BUeGhZpxa2i9OhXxAJ0kUFj0mMX6OvE4whO5aDDaGpLV6NYQkpMMBStp5EhkSQN4Q3PvQHwUk0DkPeAOx+r9NVU296M3jsI3b6ZH/il3W5Eyz7fRoZi9dx8J1tJiz5R/di6r1b33VPM7gJssPEy+89a5RnPRbHaekUZJ8b6vafIZPYRX/hShd12cDM5z4AacdeAgaJOq3JUPOi+jJJL/8wG7h4c+2KK16J5H0gjxSxKlb5ygnyiH6JEKcLyvJbl/FyVzgUYRb4L/uREF3VCvRn4hzTsD011RPOnNORtx9P1tvnaza5sCM/8WJ4mK2wgxndsv1BA7T/inTltfxNt2WJnmvI7rq+f45+0LrSCfNZ6PBv4uGdB8Tconan8Cz/oNlqILsHkAxh+P9qQdXU9KH7Tb23c4mWtLI19ZnkJtd3Yr3U7XnsrNJV/25mGpusejnICWTrW40alB7ICl3hdGk/RCBDIHSvCCWyU5wvLuQXczipVLqDKrqV99NZd7x4Ur2KrgALtzAkVnhgXYGMiA0VnQhc20/4j+iQ0KjQIp4B6HHIvMUurl3vpddMY7mUxz49ePpN1GZmKz0a1BPN8BI1TjGKtxltzKWX0KmUVjqQHfJ8rISGX4MqeFa0yRnvbK32PGkY="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
