package kz.btsd.messenger.bot.api.model.command

import io.swagger.annotations.ApiModel
import io.swagger.annotations.ApiModelProperty
import kz.btsd.messenger.bot.api.model.peer.Peer
import kz.btsd.messenger.bot.api.validation.LocalId
import kz.btsd.messenger.bot.api.validation.TimeUuid
import javax.validation.Valid

@ApiModel(description = "Forward message", parent = Command::class)
data class ForwardMessage(
    @ApiModelProperty(
        notes = "Message ID generated by Bot. Can be any string. Bot will receive MessageIdAssigned update with localId - messageId match",
        example = "804d1bbd-901f-470a-b1b8-1859277a7803"
    )
    @get:LocalId
    val localId: String? = null,

    @ApiModelProperty(notes = "Peer to send this message from")
    @get:Valid
    val fromDialog: Peer,

    @ApiModelProperty(notes = "Peer to send this message to")
    @get:Valid
    val toDialog: Peer,

    @ApiModelProperty(notes = "ID of message to send")
    @get:TimeUuid(attributeName = "localId")
    val messageId: String
) : Command("ForwardMessage")
